# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_PROJECTS/RHV4.0_FPGA/RH_BLINKY.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0.xci
# IP: The module: 'design_1_util_ds_buf_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_PROJECTS/RHV4.0_FPGA/RH_BLINKY.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_PROJECTS/RHV4.0_FPGA/RH_BLINKY.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/FPGA_PROJECTS/RHV4.0_FPGA/RH_BLINKY.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0.xci
# IP: The module: 'design_1_util_ds_buf_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_PROJECTS/RHV4.0_FPGA/RH_BLINKY.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_PROJECTS/RHV4.0_FPGA/RH_BLINKY.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
